experiment_name: "ResNet18_Encoder"
description: "SWEEP-Net"

data:
  dataset_path: "/media/temporaryuser3/STORAGE/SEED-V/preprocessed_eeg"
  save_path: "/media/temporaryuser3/STORAGE/ERO/"
  dataset_mode: "eeg"
  encoding_method: "direct"
  num_timesteps: 32
  window_size:  200
  sampling_rate: 200
  step_size: 100
  grid_size:  32
  freq_bands: 5
  num_channels: 62
  train_split: 0.8
  num_workers: 4
  prefetch_factor: 4
  preload_ram: false
  n_emotions: 5

mask:
  type: "Differential"
  sigma: 0.25
  radius: 0.7

model:
  type: "SpikingUNet"
  encoder_type: "ResNet18"
  reccurent_decoder: false
  vit_integration: false
  gc_integration: false
  encoder_mode: "cnn"
  in_channels: 5
  num_classes: 5
  dropout: 0.2
  vit_dropout: 0.3

neuron_params:
  spike_model: "ALIF" 
  beta: 0.9
  threshold: 0.5
  decay_adapt: 0.9
  gamma_adapt: 0.2
  spike_grad_alpha: 2.0
  learn_slope: false
  learn_threshold: true
  learn_beta: true
  learn_gamma: false
  learn_decay: false
  

training:
  warmup_epochs: 0
  phase_1_epochs: 300
  phase_2_epochs: 50
  phase_3_epochs: 50
  batch_size: 64
  learning_rate: 0.001
  weight_decay: 0.01
  accumulation_steps: 1

loss:
  smooth: 0.0
  lambda_seg: 0.0
  lambda_con: 0.0
  lambda_class: 1.0
  lambda_fire: 0.0
  target_rate: 0.1
  alpha: 0.3
  beta: 0.7

logging:
  project_name: "snn-encoding-showdown"
  run_name: "ResNet18_Encoder"
  tags: ["resnet18", "gc", "tsm"]
  offline: false 
  log_interval: 1