phase: "1b"
warmup_epochs: 10
phase_1_epochs: 150
phase_2_epochs: 0
phase_3_epochs: 0
batch_size: 4
learning_rate: 0.0001
weight_decay: 0.01
accumulation_steps: 2
bagging: true
freeze_encoder_epochs: 25
use_supmoco: true
supmoco_queue_size: 512
supmoco_feature_dim: 128
supmoco_momentum: 0.999
temporal_decay_enabled: true
temporal_decay_factor: 0.999
pk_subject_diverse_k: false
